version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}  # この部分を変更
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}  # この部分はそのまま
      POSTGRES_USER: ${POSTGRES_USER:-app}  # この部分もそのまま
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
